language: cpp
sudo: required
dist: precise

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libxxf86vm-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      git clone https://gist.github.com/1faa40c2df51e3a9ee55.git amd;
      cd amd;
      bash amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      mkdir ${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${HOME}/AMDAPPSDK/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${HOME}/AMDAPPSDK;
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${HOME}/AMDAPPSDK/lib/x86_64:${LD_LIBRARY_PATH};
      cd ..;
      chmod a+x ${HOME}/AMDAPPSDK/bin/x86_64/clinfo;
      ${HOME}/AMDAPPSDK/bin/x86_64/clinfo;
    fi

compiler:
- clang
- gcc

os:
- linux
- osx

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make test
  - if [ $? != 0 ]; cat Testing/Temporary/LastTest.log; fi

# after_success:

branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email: true

env:
  global:
  - LANG="en_US.UTF-8"
